### STAGE 1: Build ###
FROM node:lts-alpine  as frontend

RUN mkdir -p /app/public

WORKDIR /app

COPY . .

RUN npm i -g @adonisjs/cli

RUN npm install

COPY .env.example .env

RUN adonis migration:run

RUN adonis seed

EXPOSE 3333

CMD [ "adonis", "serve" ]
